# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postermaker', '0003_auto_20160720_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='_category_list',
            field=models.CharField(db_column='category_list', default='', max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_profile_image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_profile_image_url',
            field=models.URLField(default=''),
        ),
    ]
